---
ID: "6ab69f8f-0b05-483d-9f9d-59de3b2b7c65"
Parent: "5551cb12-8e44-433c-a68e-129b8e5a52e9"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Forms/Condition Settings/Condition Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180517T074956Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
