---
ID: "b515bc81-1341-48b6-b761-aa7e060a1bda"
Parent: "5b672865-55d2-413e-b699-fdfc7e732ccf"
Template: "5b672865-55d2-413e-b699-fdfc7e732ccf"
Path: /sitecore/templates/System/Forms/Fields/List/__Standard Values
DB: master
SharedFields:
- ID: "492361e0-72d8-4847-82ba-ebfc235cf57b"
  Hint: Display Field Name
  Value: __Display name
- ID: "589a7ade-81d4-4a60-b9e2-7eaf6ae8a563"
  Hint: Field Type
  Value: "{E0CFADEE-1AC0-471D-A820-2E70D1547B4B}"
- ID: "78778432-6327-4cea-a28b-e190e3541d28"
  Hint: Value Field Name
  Value: Value
- ID: "d99833ea-238a-4505-90ef-c69bf3eba946"
  Hint: Is Tracking Enabled
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160919T131752Z
    - ID: "71ffd7b2-8b09-4f7b-8a66-1e4cef653e8d"
      Hint: Title
      Value: Label
