---
ID: "0e723521-4594-4785-aece-ceb7bb2fb4e0"
Parent: "5ed1d26c-5a78-42b7-bc71-796ee427fe8b"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/PropertyGridForm/PageSettings/Settings
DB: core
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Property Editor Settings
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161014T095041Z
