---
ID: "26a1de26-caf0-4934-8374-d4f7688b3763"
Parent: "9121d435-48b8-4649-9d13-03d680474fad"
Template: "9121d435-48b8-4649-9d13-03d680474fad"
Path: /sitecore/templates/System/Forms/Fields/Dropdown List/__Standard Values
DB: master
SharedFields:
- ID: "6bf5048d-fbbd-4839-9f18-4412d4e11834"
  Hint: Show Empty Item
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161125T102906Z
    - ID: "71ffd7b2-8b09-4f7b-8a66-1e4cef653e8d"
      Hint: Title
      Value: Label
