---
ID: "4f485284-4119-4c52-b3db-0fcc755cfc9f"
Parent: "52fec879-7d8d-46d3-bbb2-131293957709"
Template: "52fec879-7d8d-46d3-bbb2-131293957709"
Path: /sitecore/templates/System/Forms/Fields/Password Confirmation/__Standard Values
DB: master
SharedFields:
- ID: "10e5829a-1943-4597-b9ee-406ce3d13e13"
  Hint: Validations
  Type: Treelist
  Value: "{83E96D09-11C8-4132-8A8A-76D8DB8208D6}"
- ID: "589a7ade-81d4-4a60-b9e2-7eaf6ae8a563"
  Hint: Field Type
  Value: "{6293530F-36A1-4CA6-A2E6-C59C9343F096}"
- ID: "71061c01-a495-4bf3-a52c-d378346bfae2"
  Hint: Max Length
  Value: 255
- ID: "8a43af61-0812-4b37-a343-96cde3f12bb1"
  Hint: Required
  Type: Checkbox
  Value: 1
- ID: "90c4f94c-ec2c-4ee4-b4c8-f3e29cbe630e"
  Hint: Allow Save
  Type: Checkbox
  Value: 0
- ID: "9f7da002-7b86-436b-8dda-7efe5837b88e"
  Hint: Min Length
  Value: 6
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161128T140203Z
    - ID: "49c676d7-aeed-4f95-9cff-cfa9c55c7718"
      Hint: Confirm Password Label
      Value: Confirm password
    - ID: "71ffd7b2-8b09-4f7b-8a66-1e4cef653e8d"
      Hint: Title
      Value: Password
