---
ID: "eb802e92-9120-447c-91d2-de8c763a3831"
Parent: "0908030b-4564-42ea-a6fa-c7a5a2d921a8"
Template: "0908030b-4564-42ea-a6fa-c7a5a2d921a8"
Path: /sitecore/templates/System/Forms/Fields/Input/__Standard Values
DB: master
SharedFields:
- ID: "589a7ade-81d4-4a60-b9e2-7eaf6ae8a563"
  Hint: Field Type
  Value: "{4EE89EA7-CEFE-4C8E-8532-467EF64591FC}"
- ID: "71061c01-a495-4bf3-a52c-d378346bfae2"
  Hint: Max Length
  Value: 255
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "d99833ea-238a-4505-90ef-c69bf3eba946"
  Hint: Is Tracking Enabled
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160919T131742Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "71ffd7b2-8b09-4f7b-8a66-1e4cef653e8d"
      Hint: Title
      Value: Label
