---
ID: "6fa3a73f-19ed-4442-ae94-c8c8e8e96c89"
Parent: "6abee1f2-4ab4-47f0-ad8b-bdb36f37f64c"
Template: "6abee1f2-4ab4-47f0-ad8b-bdb36f37f64c"
Path: /sitecore/templates/System/Forms/Form/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{CFEE7B51-8505-45CE-B843-9358F827DF87}"
- ID: "589a7ade-81d4-4a60-b9e2-7eaf6ae8a563"
  Hint: Field Type
  Value: "{3A4DF9C0-7C82-4415-90C3-25440257756D}"
- ID: "9eb86f19-2e5d-48db-9795-0ee4868eff11"
  Hint: Is Ajax
  Type: Checkbox
  Value: 1
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "c0ce58b7-2592-439d-b197-ca27bf69f7b2"
  Hint: Is Robot Detection Enabled
  Type: Checkbox
  Value: 1
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{6590E671-6D5E-449C-A85D-9D4BA36DC56B}" />
- ID: "d99833ea-238a-4505-90ef-c69bf3eba946"
  Hint: Is Tracking Enabled
  Type: Checkbox
  Value: 1
- ID: "fce03b41-4cbb-4f7f-920f-ff04f12fa896"
  Hint: Scripts
  Value: "jquery-3.4.1.min.js|jquery.validate.min.js|jquery.validate.unobtrusive.min.js|jquery.unobtrusive-ajax.min.js|form.validate.js|form.tracking.js|form.conditions.js"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160805T123000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
