---
ID: "b87db9a4-47d5-48f3-8d5d-1faced6e2bf6"
Parent: "6abee1f2-4ab4-47f0-ad8b-bdb36f37f64c"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Forms/Form/Settings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Software/32x32/window_application_edit.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160718T085912Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
