---
ID: "29ca5a6a-af8a-4951-83ef-983eb9b4607e"
Parent: "81fe389a-fdc7-4eca-a5a9-4be3aca0c69a"
Template: "81fe389a-fdc7-4eca-a5a9-4be3aca0c69a"
Path: /sitecore/templates/System/Forms/Fields/List Box/__Standard Values
DB: master
SharedFields:
- ID: "3f67be6a-f3f0-41c5-b379-c6af29685666"
  Hint: Rows
  Value: 4
- ID: "589a7ade-81d4-4a60-b9e2-7eaf6ae8a563"
  Hint: Field Type
  Value: "{222A2121-D370-4C6F-80A3-03C930B718BF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161125T102906Z
    - ID: "71ffd7b2-8b09-4f7b-8a66-1e4cef653e8d"
      Hint: Title
      Value: Label
