---
ID: "abb63b88-1b82-4c71-880d-aa5af51da20d"
Parent: "7d13b4b2-3c4d-4639-8e16-6169e3e734c5"
Template: "7d13b4b2-3c4d-4639-8e16-6169e3e734c5"
Path: /sitecore/templates/Project/FormsExtensionsTester/Pages/ContentPage/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{F5D69E95-A6A1-43DF-9BB9-41B83FB4208D}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200607T111238Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
