---
ID: "f7f02291-b78f-45e2-8fd3-37cf14fbfd5d"
Parent: "84ed565a-bec9-46d4-9603-6e0516580832"
Template: "84ed565a-bec9-46d4-9603-6e0516580832"
Path: /sitecore/templates/System/Forms/Fields/Field/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160919T132355Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
