---
ID: "fb557c1a-96f1-45f3-a778-c911fb109d6a"
Parent: "05fe45d4-b9c7-40de-b767-7c5abe7119f9"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/System/Forms/Submit Action Definition/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170403T120109Z
