---
ID: "edacb8d9-eed2-4ff2-90b5-20663a118af8"
Parent: "91454fbb-7aa6-40f3-bd9a-49b2a42bf5e0"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Modules/FormsExtensions/Extended Value Provider Settings/Value Provider Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180621T150057Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
