---
ID: "989a09a8-ed6a-4c86-ab58-a6c708c0e236"
Parent: "41eeec31-bf4c-4465-8638-77bdc96b5577"
Template: "41eeec31-bf4c-4465-8638-77bdc96b5577"
Path: /sitecore/templates/System/Forms/Meta Data/Conditions/Action Type/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180814T125837Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ffd9bcf2-b4b0-4d24-8bd0-952c7df05a3b"
      Hint: Text
      Value: "[actionType] [field]"
